# Generated by Django 3.2 on 2021-04-25 15:59

# 第一次执行生成迁移文件时，系统会自动扫描所有安装的子应用，全部生成迁移文件
# Django自带的子应用默认已经生成了迁移文件(去系统auth子应用可见)，但是未迁移，因为数据库是用户指定的
# python manage.py makemigrations 生成迁移文件

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='书籍名')),
                ('pub_date', models.DateField(null=True, verbose_name='发表日期')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '书籍信息',
                'db_table': 'bookinfo',
            },
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0, verbose_name='性别')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='描述')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='book.bookinfo', verbose_name='书籍id')),
            ],
            options={
                'verbose_name': '人物信息',
                'db_table': 'personinfo',
            },
        ),
    ]
